FROM golang:1.13 AS gobuilder

ARG APPNAME

WORKDIR /go/src/github.mpi-internal.com/Yapo/${APPNAME}
COPY ./ .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -o /app.linux cmd/${APPNAME}/main.go

FROM alpine:3.11

# Package tzdata is needed before setting TZ ENV variable
RUN apk update && apk add ca-certificates && apk add -U tzdata
ENV TZ America/Santiago

# Copy zoneinfo file and then remove cache
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime && rm -rf /var/cache/apk/*

EXPOSE 8080
WORKDIR /home/user/app/
COPY --from=gobuilder /app.linux .

CMD ["./app.linux"]

ARG APPNAME
ENV PS1="\[\e[1;32m\]$APPNAME \[\e[1;31m\][`pwd`] # \[\e[0m\]"

ARG GIT_COMMIT
RUN touch /home/user/app/$GIT_COMMIT
